dbfilename redis_queue.rdb
dir /home/rohy/evalaivr/evaluation/config/pids
pidfile /home/rohy/evalaivr/evaluation/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/rohy/evalaivr/evaluation/config/redis_queue.acl
